name: Package Helmfiles

on:
  workflow_dispatch:

jobs:
  dump-version:
    runs-on: ubuntu-latest
    steps:


      - uses: actions/checkout@v2


      - name: Helm Package
        run: |
          sed -e 's/ZZZZZ/100.22.3/' build/helm/listshop-web/Chart.yaml > temp.txt
          mv temp.txt build/helm/listshop-web/Chart.yaml
          cat build/helm/listshop-web/Chart.yaml
