name: Package Helmfiles

on:
  workflow_dispatch:

jobs:
  dump-version:
    runs-on: ubuntu-latest
    steps:


      - uses: actions/checkout@v2


      - name: Update version in charts
        run: |
          GITHUB_REF=1.2.3.4
          sed -e "s|ZZZZZ|${GITHUB_REF##*/}|" build/helm/listshop-web/Chart.yaml > temp.txt
          cat temp.txt
